In [108]:
# ==============================================================================
# Importar as bibliotecas necessárias para manipulação,
# análise e visualização inicial dos dados.
# ==============================================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [109]:
#Leitura dos arquivos CSV do projeto
df_shades = pd.read_csv("../data/raw/thepudding_allShades.csv")

In [110]:
# Descobrindo o tamanho do dataset
print(df_shades.shape)

(6816, 13)

In [111]:
# Informações gerais sobre o DataFrame, incluindo o número de entradas, tipos de dados e contagem de valores não nulos
df_shades.info()

<class 'pandas.DataFrame'>
RangeIndex: 6816 entries, 0 to 6815
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   brand        6816 non-null   str
 1   product      6816 non-null   str
 2   url          6816 non-null   str
 3   description  6816 non-null   str
 4   imgSrc       6816 non-null   str
 5   imgAlt       6816 non-null   str
 6   name         4955 non-null   str
 7   specific     4905 non-null   str
 8   colorspace   6816 non-null   str
 9   hex          6816 non-null   str
 10  hue          6816 non-null   float64
 11  sat          6816 non-null   float64
 12  lightness    6816 non-null   float64
dtypes: float64(3), str(10)
memory usage: 692.4 KB

In [112]:
#TRADUÇÃO DAS COLUNAS - Para melhor compreensão, as colunas do DataFrame foram traduzidas para o português. A tradução foi feita de forma literal, mantendo o significado original das colunas.
df_shades.rename(columns= {
'brand': 'marca',
    'product': 'produto',
    'url': 'url_produto',
    'description': 'descricao',
    'imgSrc': 'url_imagem',
    'imgAlt': 'texto_alt_imagem',
    'name': 'nome_tom',
    'specific': 'tom_especifico',
    'colorspace': 'espaco_cores',
    'hex': 'codigo_hex',
    'hue': 'matiz',
    'sat': 'saturacao',
    'lightness': 'luminosidade'
}, inplace=True)

In [113]:
df_shades.head(10)

                     marca              produto                                                        url_produto                                                     descricao                                              url_imagem                                     texto_alt_imagem nome_tom tom_especifico espaco_cores codigo_hex      matiz  saturacao  luminosidade
0  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586  355N (medium skin with a neutral golden undertone)  selected    https://images.ulta.com/is/image/Ulta/2551437sw?$tn$   355N (medium skin with a neutral golden undertone)      NaN           355N          RGB    #A06F4A  25.813953   0.367521      0.458824
1  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586                100N (very fair skin with a neutral undertone)  https://images.ulta.com/is/image/Ulta/2551414sw?$50px$       100N (very fair skin with a neutral undertone)      NaN           100N          RGB    #F1E7DB  32.727273   0.440000      0.901961
2  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586                   110C (very fair skin with a cool undertone)  https://images.ulta.com/is/image/Ulta/2551412sw?$50px$          110C (very fair skin with a cool undertone)      NaN           110C          RGB    #F0E7DB  34.285714   0.411765      0.900000
3  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586                   120W (very fair skin with a warm undertone)  https://images.ulta.com/is/image/Ulta/2551419sw?$50px$          120W (very fair skin with a warm undertone)      NaN           120W          RGB    #EFD0AE  31.384615   0.670103      0.809804
4  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586           130N (very fair skin with a neutral pink undertone)  https://images.ulta.com/is/image/Ulta/2551416sw?$50px$  130N (very fair skin with a neutral pink undertone)      NaN           130N          RGB    #D5C1AA  32.093023   0.338583      0.750980
5  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586               140N (fair skin with a neutral peach undertone)  https://images.ulta.com/is/image/Ulta/2551415sw?$50px$      140N (fair skin with a neutral peach undertone)      NaN           140N          RGB    #DBC2A9  30.000000   0.409836      0.760784
6  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586                  150W (fair skin with a warm beige undertone)  https://images.ulta.com/is/image/Ulta/2551418sw?$50px$         150W (fair skin with a warm beige undertone)      NaN           150W          RGB    #EFCDA8  31.267606   0.689320      0.798039
7  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586                 160C (fair skin with a cool golden undertone)  https://images.ulta.com/is/image/Ulta/2551417sw?$50px$        160C (fair skin with a cool golden undertone)      NaN           160C          RGB    #DEC5A7  32.727273   0.454545      0.762745
8  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586                       200W (light skin with a warm undertone)  https://images.ulta.com/is/image/Ulta/2551420sw?$50px$              200W (light skin with a warm undertone)      NaN           200W          RGB    #EDCAA1  32.368421   0.678571      0.780392
9  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586             210N (light skin with a neutral golden undertone)  https://images.ulta.com/is/image/Ulta/2551423sw?$50px$    210N (light skin with a neutral golden undertone)      NaN           210N          RGB    #E8C9AA  30.000000   0.574074      0.788235

In [114]:
# OBJETIVO: Fazer um raio-X (diagnóstico inicial) de todas as colunas da base de dados.
# Percorre cada coluna do DataFrame 'df_shades', uma por uma, para analisar sua qualidade e estrutura
for coluna in df_shades.columns:
    # Imprime o nome da coluna atual formatado entre traços para organização visual no terminal
    print(f"\n--- {coluna} ---")
    # Exibe o tipo de dado armazenado na coluna (ex: str, float64, int64)
    print(f"Tipo: {df_shades[coluna].dtype}")
    # Conta e exibe a quantidade de valores ÚNICOS (distintos/diferentes) presentes na coluna
    print(f"Valores únicos: {df_shades[coluna].nunique()}")
    # Conta e exibe a quantidade total de valores NULOS/faltantes (NaN) na coluna
    print(f"Nulos: {df_shades[coluna].isna().sum()}")

--- marca ---
Tipo: str
Valores únicos: 107
Nulos: 0

--- produto ---
Tipo: str
Valores únicos: 328
Nulos: 0

--- url_produto ---
Tipo: str
Valores únicos: 328
Nulos: 0

--- descricao ---
Tipo: str
Valores únicos: 5623
Nulos: 0

--- url_imagem ---
Tipo: str
Valores únicos: 6816
Nulos: 0

--- texto_alt_imagem ---
Tipo: str
Valores únicos: 5802
Nulos: 0

--- nome_tom ---
Tipo: str
Valores únicos: 1219
Nulos: 1861

--- tom_especifico ---
Tipo: str
Valores únicos: 1723
Nulos: 1911

--- espaco_cores ---
Tipo: str
Valores únicos: 1
Nulos: 0

--- codigo_hex ---
Tipo: str
Valores únicos: 6254
Nulos: 0

--- matiz ---
Tipo: float64
Valores únicos: 1484
Nulos: 0

--- saturacao ---
Tipo: float64
Valores únicos: 3194
Nulos: 0

--- luminosidade ---
Tipo: float64
Valores únicos: 407
Nulos: 0

Algumas marcas não dão o nome do tom (nome_tom), então eu suponho que podemos usar apenas a coluna tom_especifico. Então vamos analisar apenas elas pra ver se vale a pena mesmo excluir a coluna nome_tom e manter apenas tom_especfico

In [115]:
# Exibe informações gerais sobre as colunas 'nome_tom' e 'tom_especifico',
# mostrando a contagem de valores não nulos (preenchidos) e o tipo de dados de cada uma
df_shades[["nome_tom", "tom_especifico"]].info()

<class 'pandas.DataFrame'>
RangeIndex: 6816 entries, 0 to 6815
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   nome_tom        4955 non-null   str
 1   tom_especifico  4905 non-null   str
dtypes: str(2)
memory usage: 106.6 KB

In [116]:
# 1. Conta quantas linhas possuem AMBAS as colunas preenchidas (notna() em ambas)
print("1. Ambos preenchidos:",
      (
          df_shades["nome_tom"].notna() &
          df_shades["tom_especifico"].notna()
      ).sum())

# 2. Conta quantas linhas têm 'nome_tom' preenchido, mas 'tom_especifico' vazio (isna())
print("2. Nome preenchido / específico nulo:",
      (
          df_shades["nome_tom"].notna() &
          df_shades["tom_especifico"].isna()
      ).sum())

# 3. Conta quantas linhas têm 'nome_tom' vazio, mas 'tom_especifico' preenchido
print("3. Nome nulo / específico preenchido:",
      (
          df_shades["nome_tom"].isna() &
          df_shades["tom_especifico"].notna()
      ).sum())

# 4. Conta quantas linhas estão completamente vazias em AMBAS as colunas
print("4. Ambos nulos:",
      (
          df_shades["nome_tom"].isna() &
          df_shades["tom_especifico"].isna()
      ).sum())

1. Ambos preenchidos: 3044
2. Nome preenchido / específico nulo: 1911
3. Nome nulo / específico preenchido: 1861
4. Ambos nulos: 0

In [117]:
# Exibe as primeiras 160 linhas das colunas 'tom_especifico' e 'nome_tom'
# para inspecionar visualmente como os dados estão preenchidos lado a lado
df_shades[['tom_especifico', 'nome_tom']].head(160)

    tom_especifico     nome_tom
0             355N          NaN
1             100N          NaN
2             110C          NaN
3             120W          NaN
4             130N          NaN
..             ...          ...
155             32  Medium Warm
156             34  Medium Cool
157             35  Medium Warm
158             36  Medium Cool
159             39  Tan Neutral

[160 rows x 2 columns]

Unificação das informações de identificação do tom

A análise mostrou que não existe nenhum registro com nome_tom e tom_especifico simultaneamente nulos. Portanto, todos os registros possuem pelo menos uma informação de identificação do tom.

Diante disso, foi avaliada a possibilidade de unificar essas informações.

As colunas possuem características diferentes: nome_tom contém nomes comerciais ou criativos atribuídos pelas marcas, sem uma padronização consistente entre os produtos, enquanto tom_especifico apresenta informações mais recorrentes e estruturadas para identificação do tom.

Como o objetivo das análises posteriores é trabalhar com uma única informação de identificação do tom, optei por criar a coluna tom_unificado. Nessa nova coluna, será priorizado o valor de tom_especifico e, nos casos em que ele estiver ausente, será utilizado o valor disponível em nome_tom.

Dessa forma, preservo a informação disponível nos dados, reduzo a presença de valores nulos na variável que poderá ser utilizada para análise e mantenho as duas colunas originais para rastreabilidade da transformação.

In [118]:
# Cria uma coluna unificada aproveitando o nome_tom onde tom_especifico for NaN
df_shades["tom_unificado"] = df_shades["tom_especifico"].fillna(df_shades["nome_tom"])
print(df_shades[["nome_tom", "tom_especifico", "tom_unificado"]])

        nome_tom tom_especifico tom_unificado
0            NaN           355N          355N
1            NaN           100N          100N
2            NaN           110C          110C
3            NaN           120W          120W
4            NaN           130N          130N
...          ...            ...           ...
6811        Sand              5             5
6812        Dark            NaN          Dark
6813         NaN       Shade 11      Shade 11
6814  Naked Dark            NaN    Naked Dark
6815  Bare Mocha             20            20

[6816 rows x 3 columns]

In [119]:
#Verificando se deu certo e não temos nada nulo na coluna unificada
print(f"Nulos: {df_shades['tom_unificado'].isna().sum()}")

Nulos: 0

In [120]:
# Verificando se temos dados duplicados
df_shades.duplicated().sum()

np.int64(0)

In [121]:

# Define para não quebrar a exibição em várias linhas/blocos
pd.set_option('display.expand_frame_repr', False)

# Opcional: aumenta o limite de caracteres de largura máxima da tela
pd.set_option('display.width', 1000)

# Opcional: aumenta o limite de caracteres por coluna antes de colocar "..."
pd.set_option('display.max_colwidth', None)

In [122]:
# Seleciona e exibe na tela apenas as colunas 'descricao' e 'texto_alt_imagem' lado a lado,
# permitindo comparar visualmente o conteúdo de ambas para as primeiras e últimas linhas do dataset
print(df_shades[["descricao", "texto_alt_imagem"]])

                                                                     descricao                                     texto_alt_imagem
0                 355N (medium skin with a neutral golden undertone)  selected   355N (medium skin with a neutral golden undertone)
1                               100N (very fair skin with a neutral undertone)       100N (very fair skin with a neutral undertone)
2                                  110C (very fair skin with a cool undertone)          110C (very fair skin with a cool undertone)
3                                  120W (very fair skin with a warm undertone)          120W (very fair skin with a warm undertone)
4                          130N (very fair skin with a neutral pink undertone)  130N (very fair skin with a neutral pink undertone)
...                                                                        ...                                                  ...
6811  5 Sand for medium skintones with neutral to peachy undertones - Selected                                        5 Sand 1.7 oz
6812                                                           Dark - Selected                 Dark 0.29 oz/ 8.5 g Clean at Sephora
6813                                          Shade 11 dark neutral - Selected                                 Shade 11 1 oz/ 30 mL
6814                                                     Naked Dark - Selected                            Naked Dark 0.26 oz/ 7.3 g
6815                                                  Bare Mocha 20 - Selected                                   Bare Mocha 20 1 oz

[6816 rows x 2 columns]

In [123]:
# ==============================================================================
# ANÁLISE - DESCRIÇÃO X TEXTO ALT DA IMAGEM
# ==============================================================================

# Vamos identificar quais valores aparecem em "descricao"
# mas não são encontrados em "texto_alt_imagem".

diferentes = df_shades[
    df_shades["descricao"] != df_shades["texto_alt_imagem"]
]

print("Quantidade de registros diferentes:", len(diferentes))

print(
    diferentes[
        ["descricao", "texto_alt_imagem"]
    ].head(30).to_string(index=False)
)

Quantidade de registros diferentes: 3101
                                                                         descricao                                                         texto_alt_imagem
                      355N (medium skin with a neutral golden undertone)  selected                       355N (medium skin with a neutral golden undertone)
                  Shell 1W1 (very fair beige w/ golden, warm undertones)  selected                   Shell 1W1 (very fair beige w/ golden, warm undertones)
                    Linen 1N1 (very fair beige w/ neutral undertones) OUT OF STOCK                        Linen 1N1 (very fair beige w/ neutral undertones)
             Porcelain 1N2 (fair beige w/ peachy, neutral undertones) OUT OF STOCK                 Porcelain 1N2 (fair beige w/ peachy, neutral undertones)
          Buff 2W2 (light to medium beige w/ golden, warm undertones) OUT OF STOCK              Buff 2W2 (light to medium beige w/ golden, warm undertones)
                 Camel 3N1 (medium pinky beige w/ neutral undertones) OUT OF STOCK                     Camel 3N1 (medium pinky beige w/ neutral undertones)
             Noisette 3N2 (medium peachy beige w/ neutral undertones) OUT OF STOCK                 Noisette 3N2 (medium peachy beige w/ neutral undertones)
                     Bamboo 4W2 (very tan w/ golden, warm undertones) OUT OF STOCK                         Bamboo 4W2 (very tan w/ golden, warm undertones)
                      Maple 5W2 (very dark auburn w/ warm undertones) OUT OF STOCK                          Maple 5W2 (very dark auburn w/ warm undertones)
                                                 Shade 3 (light/neutral)  selected                                                  Shade 3 (light/neutral)
                                                     Shade 1 - Fair Cool  selected                                                      Shade 1 - Fair Cool
                                                     Shade 1 - Fair Cool  selected                                                      Shade 1 - Fair Cool
                          Fair (very fair skin w/ warm yellow undertone)  selected                           Fair (very fair skin w/ warm yellow undertone)
Medium Neutral 33 (medium complexion with subtle neutral pink undertone)  selected Medium Neutral 33 (medium complexion with subtle neutral pink undertone)
     Fair Neutral 10.5 (very fair complexion with neutral undertones) OUT OF STOCK         Fair Neutral 10.5 (very fair complexion with neutral undertones)
                      Medium 54 N (medium sesame with neutral undertone)  selected                       Medium 54 N (medium sesame with neutral undertone)
                                                Medium 150 (medium sand)  selected                                                 Medium 150 (medium sand)
                                                Medium 150 (medium sand)  selected                                                 Medium 150 (medium sand)
                                            Medium 145 (medium taupe) OUT OF STOCK                                                Medium 145 (medium taupe)
                           Light 002 (near-white with neutral undertone)  selected                            Light 002 (near-white with neutral undertone)
                              Light 004 (fair with neutral undertone) OUT OF STOCK                                  Light 004 (fair with neutral undertone)
                            Light 006 (fair pink with warm undertone) OUT OF STOCK                                Light 006 (fair pink with warm undertone)
                          Light 008 (fair golden with warm undertone) OUT OF STOCK                              Light 008 (fair golden with warm undertone)
                        Light 012 (light pink with neutral undertone) OUT OF STOCK                            Light 012 (light pink with neutral undertone)
                         Light 015 (light golden with warm undertone) OUT OF STOCK                             Light 015 (light golden with warm undertone)
                                Light 018 (light with cool undertone) OUT OF STOCK                                    Light 018 (light with cool undertone)
                             Light 021 (light with neutral undertone) OUT OF STOCK                                 Light 021 (light with neutral undertone)
                                Light 024 (light with warm undertone) OUT OF STOCK                                    Light 024 (light with warm undertone)
                     Medium 027 (light-medium with neutral undertone) OUT OF STOCK                         Medium 027 (light-medium with neutral undertone)
                           Medium 054 (medium with neutral undertone) OUT OF STOCK                               Medium 054 (medium with neutral undertone)

In [124]:
# Compara as colunas 'descricao' e 'texto_alt_imagem' para verificar a frequência 
# de valores idênticos (True) e diferentes (False)
(df_shades['descricao'] == df_shades['texto_alt_imagem']).value_counts()
(df_shades['descricao'] == df_shades['texto_alt_imagem']).value_counts()

True     3715
False    3101
Name: count, dtype: int64

In [125]:
# Remove o texto_alt_imagem da descricao para ver o que sobra no final
sobra = df_shades.apply(
    lambda row: str(row['descricao']).replace(str(row['texto_alt_imagem']), '').strip(), 
    axis=1
)

# Mostra todos os sufixos/diferenças e quantas vezes eles aparecem
sobra.value_counts()

                                                                            3715
selected                                                                     181
OUT OF STOCK                                                                 131
deep with warm undertones                                                      6
for medium skin with warm undertones                                           6
                                                                            ...
5 Sand for medium skintones with neutral to peachy undertones - Selected       1
Dark - Selected                                                                1
Shade 11 dark neutral - Selected                                               1
Naked Dark - Selected                                                          1
Bare Mocha 20 - Selected                                                       1
Name: count, Length: 2410, dtype: int64

As duas colunas apresentam conteúdo altamente semelhante. Em 3.715 registros os valores são idênticos, enquanto nos demais a descricao apresenta principalmente informações adicionais relacionadas ao status do produto, como selected e OUT OF STOCK, além de alguns complementos relacionados à descrição do tom.

Como essas informações adicionais não serão utilizadas nas análises do projeto, optamos por manter apenas texto_alt_imagem, que contém a informação descritiva necessária.

In [126]:
# Remove a coluna descricao original
df_shades = df_shades.drop(columns=['descricao'])

# Renomeia texto_alt_imagem para descricao
df_shades = df_shades.rename(columns={'texto_alt_imagem': 'descricao'})

In [127]:
df_shades.head()

                     marca              produto                                                        url_produto                                              url_imagem                                            descricao nome_tom tom_especifico espaco_cores codigo_hex      matiz  saturacao  luminosidade tom_unificado
0  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586    https://images.ulta.com/is/image/Ulta/2551437sw?$tn$   355N (medium skin with a neutral golden undertone)      NaN           355N          RGB    #A06F4A  25.813953   0.367521      0.458824          355N
1  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586  https://images.ulta.com/is/image/Ulta/2551414sw?$50px$       100N (very fair skin with a neutral undertone)      NaN           100N          RGB    #F1E7DB  32.727273   0.440000      0.901961          100N
2  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586  https://images.ulta.com/is/image/Ulta/2551412sw?$50px$          110C (very fair skin with a cool undertone)      NaN           110C          RGB    #F0E7DB  34.285714   0.411765      0.900000          110C
3  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586  https://images.ulta.com/is/image/Ulta/2551419sw?$50px$          120W (very fair skin with a warm undertone)      NaN           120W          RGB    #EFD0AE  31.384615   0.670103      0.809804          120W
4  Anastasia Beverly Hills  Luminous Foundation  https://www.ulta.com/luminous-foundation?productId=pimprod2008586  https://images.ulta.com/is/image/Ulta/2551416sw?$50px$  130N (very fair skin with a neutral pink undertone)      NaN           130N          RGB    #D5C1AA  32.093023   0.338583      0.750980          130N

PADRONIZAÇÃO DO DATAFRAME PRA MELHOR UTILIZAÇÃO DELES NO SQL

In [128]:
# ==============================================================================
# ETAPA 1: Padronização de Texto (Para facilitar as consultas no SQL)
# ==============================================================================

# Lista com todas as colunas que contêm texto (excluímos matiz, saturacao e luminosidade por serem números)
colunas_texto = [
    'marca', 'produto', 'url_produto', 'url_imagem', 'descricao', 
    'nome_tom', 'tom_especifico', 'espaco_cores', 'codigo_hex','tom_unificado'
]

# O acessor .str do Pandas aplica a limpeza mantendo os valores nulos (NaN) intactos!
for col in colunas_texto:
    # 1. .str.strip() -> Remove espaços no início e no final do texto (ex: " tom " vira "tom")
    # 2. .str.lower() -> Transforma todo o texto em minúsculo (ex: "Ruby" vira "ruby")
    df_shades[col] = df_shades[col].str.strip().str.lower()

In [129]:
df_shades.head(10)

                     marca              produto                                                        url_produto                                              url_imagem                                            descricao nome_tom tom_especifico espaco_cores codigo_hex      matiz  saturacao  luminosidade tom_unificado
0  anastasia beverly hills  luminous foundation  https://www.ulta.com/luminous-foundation?productid=pimprod2008586    https://images.ulta.com/is/image/ulta/2551437sw?$tn$   355n (medium skin with a neutral golden undertone)      NaN           355n          rgb    #a06f4a  25.813953   0.367521      0.458824          355n
1  anastasia beverly hills  luminous foundation  https://www.ulta.com/luminous-foundation?productid=pimprod2008586  https://images.ulta.com/is/image/ulta/2551414sw?$50px$       100n (very fair skin with a neutral undertone)      NaN           100n          rgb    #f1e7db  32.727273   0.440000      0.901961          100n
2  anastasia beverly hills  luminous foundation  https://www.ulta.com/luminous-foundation?productid=pimprod2008586  https://images.ulta.com/is/image/ulta/2551412sw?$50px$          110c (very fair skin with a cool undertone)      NaN           110c          rgb    #f0e7db  34.285714   0.411765      0.900000          110c
3  anastasia beverly hills  luminous foundation  https://www.ulta.com/luminous-foundation?productid=pimprod2008586  https://images.ulta.com/is/image/ulta/2551419sw?$50px$          120w (very fair skin with a warm undertone)      NaN           120w          rgb    #efd0ae  31.384615   0.670103      0.809804          120w
4  anastasia beverly hills  luminous foundation  https://www.ulta.com/luminous-foundation?productid=pimprod2008586  https://images.ulta.com/is/image/ulta/2551416sw?$50px$  130n (very fair skin with a neutral pink undertone)      NaN           130n          rgb    #d5c1aa  32.093023   0.338583      0.750980          130n
5  anastasia beverly hills  luminous foundation  https://www.ulta.com/luminous-foundation?productid=pimprod2008586  https://images.ulta.com/is/image/ulta/2551415sw?$50px$      140n (fair skin with a neutral peach undertone)      NaN           140n          rgb    #dbc2a9  30.000000   0.409836      0.760784          140n
6  anastasia beverly hills  luminous foundation  https://www.ulta.com/luminous-foundation?productid=pimprod2008586  https://images.ulta.com/is/image/ulta/2551418sw?$50px$         150w (fair skin with a warm beige undertone)      NaN           150w          rgb    #efcda8  31.267606   0.689320      0.798039          150w
7  anastasia beverly hills  luminous foundation  https://www.ulta.com/luminous-foundation?productid=pimprod2008586  https://images.ulta.com/is/image/ulta/2551417sw?$50px$        160c (fair skin with a cool golden undertone)      NaN           160c          rgb    #dec5a7  32.727273   0.454545      0.762745          160c
8  anastasia beverly hills  luminous foundation  https://www.ulta.com/luminous-foundation?productid=pimprod2008586  https://images.ulta.com/is/image/ulta/2551420sw?$50px$              200w (light skin with a warm undertone)      NaN           200w          rgb    #edcaa1  32.368421   0.678571      0.780392          200w
9  anastasia beverly hills  luminous foundation  https://www.ulta.com/luminous-foundation?productid=pimprod2008586  https://images.ulta.com/is/image/ulta/2551423sw?$50px$    210n (light skin with a neutral golden undertone)      NaN           210n          rgb    #e8c9aa  30.000000   0.574074      0.788235          210n

In [130]:
# Cria uma coluna de ID numérico sequencial (1, 2, 3...)
df_shades['id_shade'] = range(1, len(df_shades) + 1)

# Reorganiza as colunas para colocar o 'id_shade' como a primeira coluna da tabela
colunas = ['id_shade'] + [col for col in df_shades.columns if col != 'id_shade']
df_shades = df_shades[colunas]

In [131]:
df_shades.info()

<class 'pandas.DataFrame'>
RangeIndex: 6816 entries, 0 to 6815
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_shade        6816 non-null   int64
 1   marca           6816 non-null   str
 2   produto         6816 non-null   str
 3   url_produto     6816 non-null   str
 4   url_imagem      6816 non-null   str
 5   descricao       6816 non-null   str
 6   nome_tom        4955 non-null   str
 7   tom_especifico  4905 non-null   str
 8   espaco_cores    6816 non-null   str
 9   codigo_hex      6816 non-null   str
 10  matiz           6816 non-null   float64
 11  saturacao       6816 non-null   float64
 12  luminosidade    6816 non-null   float64
 13  tom_unificado   6816 non-null   str
dtypes: float64(3), int64(1), str(10)
memory usage: 745.6 KB

In [132]:
print(df_shades['luminosidade'].describe())

count    6816.000000
mean        0.633914
std         0.162984
min         0.154902
25%         0.517647
50%         0.662745
75%         0.758824
max         0.996078
Name: luminosidade, dtype: float64

In [133]:
# ------------------------------------------------------------------------------
# ADEQUAÇÃO DA ESCALA DE LUMINOSIDADE (DE DECIMAL PARA PERCENTUAL 0-100)
# ------------------------------------------------------------------------------
# A variável 'luminosidade' varia de 0.0 a 1.0. Multiplicamos por 100 para 
# atender à regra de negócio (faixas de 0 a 100) especificada no case.
df_shades['luminosidade'] = df_shades['luminosidade'] * 100

In [134]:
# ------------------------------------------------------------------------------
# 3. CRIAÇÃO DAS FAIXAS (BINS) E RÓTULOS (MISSÃO 1 DO CASE)
# ------------------------------------------------------------------------------
# Regra do Desafio:
#  0 a 30  -> Retinto / Deep
# 31 a 50  -> Escuro / Dark
# 51 a 75  -> Médio / Medium
# 76 a 100 -> Claro / Light

# 1. BINS (PONTOS DE CORTE / FAiXAS NUMÉRICAS):
# Definimos os limites numéricos para fatiar a coluna 'luminosidade'.
# Nota: Usamos -1 ao invés de 0 no início para garantir que o valor '0' 
# seja incluído na primeira faixa (de 0 a 30).
# As 4 faixas criadas são: (-1 a 30], (30 a 50], (50 a 75], (75 a 100]
bins = [-1, 30, 50, 75, 100]
# 2. LABELS (ETIQUETAS DE TEXTO / RÓTULOS):
# Definimos os nomes que cada uma das 4 faixas numéricas vai receber.
# A ordem aqui DEVE corresponder perfeitamente à ordem das faixas dos bins.
labels = ['Retinto / Deep', 'Escuro / Dark', 'Médio / Medium', 'Claro / Light']

# 3. AGRUPAMENTO COM PD.CUT (CORTANDO OS DADOS E CRIANDO A NOVA COLUNA):
# O pd.cut pega a coluna 'luminosidade', compara cada número com as faixas em 'bins',
# e substitui pelo nome correspondente presente em 'labels'.
# O resultado é guardado na NOVA coluna chamada 'grupo_de_tom'.
df_shades['grupo_de_tom'] = pd.cut(
    df_shades['luminosidade'], # Coluna original com os números (0 a 100)
    bins=bins, # Limites numéricos onde o corte é feito
    labels=labels # Nomes em texto que serão atribuídos a cada faixa
)

# Visualização do resultado final: Exibe as primeiras 10 linhas das colunas 'luminosidade' e 'grupo_de_tom' para verificar se a categorização foi aplicada corretamente.
print(df_shades[['luminosidade', 'grupo_de_tom']].head(555))

     luminosidade    grupo_de_tom
0       45.882353   Escuro / Dark
1       90.196078   Claro / Light
2       90.000000   Claro / Light
3       80.980392   Claro / Light
4       75.098039   Claro / Light
..            ...             ...
550     64.509804  Médio / Medium
551     65.098039  Médio / Medium
552     65.098039  Médio / Medium
553     65.490196  Médio / Medium
554     69.215686  Médio / Medium

[555 rows x 2 columns]

In [135]:
# 4. VALIDAÇÃO DO RESULTADO DA CATEGORIZAÇÃO
print("\n--- Distribuição das Bases por Categoria de Tom (Visão do Mercado) ---")
print(df_shades['grupo_de_tom'].value_counts(dropna=False))

print("\n--- Percentual do Mercado por Categoria ---")
print((df_shades['grupo_de_tom'].value_counts(normalize=True) * 100).round(2).astype(str) + '%')

--- Distribuição das Bases por Categoria de Tom (Visão do Mercado) ---
grupo_de_tom
Médio / Medium    3436
Claro / Light     1822
Escuro / Dark     1337
Retinto / Deep     221
Name: count, dtype: int64

--- Percentual do Mercado por Categoria ---
grupo_de_tom
Médio / Medium    50.41%
Claro / Light     26.73%
Escuro / Dark     19.62%
Retinto / Deep     3.24%
Name: proportion, dtype: str

In [137]:
# Retorna a quantidade exata de linhas com valor ausente (NaN)
total_nulos = df_shades['grupo_de_tom'].isna().sum()
print(f"Total de valores ausentes: {total_nulos}")

Total de valores ausentes: 0

In [139]:
# Salva o CSV na pasta processed
df_shades.to_csv('../data/processed/df_shades_limpo.csv', index=False)